name: Aprendiendo GitHub Actions

run-name: ¡Estoy aprendiendo GitHub Actions!

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hola-mundo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          # Version Spec of the version to use.  Examples: 8.1
          php-version: '7.4'
          
      # Runs a single command using the runners shell
      - name: Run a PHP script
        run: php index.php
